name: "HotPotato"
author: BukkitNews
version: "1.0"
main: de.bukkitnews.hotpotato.HotPotato
api-version: "1.20"
commands:
  setup:
    description: Setup-Command
  start:
    description: Start-Command
  language:
    description: Sprache-Command
    aliases: [sprache]
  build:
    description: Build-Command
  achievement:
    description: Achievement-Command
    aliases: [erfolge]